# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

wake_on_lan:
switch:
  - platform: wake_on_lan
    mac: "b4:2e:99:a5:5a:6a"
    name: "CoolerMaster-PC"
  # turn_off:
  #  service: shell_command.turn_off_CoolerMaster-PC

#shell_command for pc:
#turn_off_TARGET: "ssh hass@CoolerMaster-PC sudo pm-suspend"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Add themes
frontend:
  themes: !include_dir_merge_named themes
input_select:
  themes:
    name: "Themes"
    icon: mdi:format-paint
    options:
      - Caule Black Rose
      - Caule Black Purple
      - Caule Black Blue
      - Caule Black Aqua
      - Caule Black Green
      - Caule Black Yellow
      - Caule Black Orange
      - Caule Black Coral
      - Caule Black Pink
      - Caule Black Gray
      - Caule Dark Rose
      - Caule Dark Purple
      - Caule Dark Blue
      - Caule Dark Aqua
      - Caule Dark Green
      - Caule Dark Yellow
      - Caule Dark Orange
      - Caule Dark Coral
      - Caule Dark Pink
      - Caule Dark Gray
      - Caule Light Rose
      - Caule Light Purple
      - Caule Light Blue
      - Caule Light Aqua
      - Caule Light Green
      - Caule Light Yellow
      - Caule Light Orange
      - Caule Light Coral
      - Caule Light Pink
      - Caule Light Gray
      - Caule Black Rose Glass
      - Caule Black Purple Glass
      - Caule Black Blue Glass
      - Caule Black Aqua Glass
      - Caule Black Green Glass
      - Caule Black Yellow Glass
      - Caule Black Orange Glass
      - Caule Black Coral Glass
      - Caule Black Pink Glass
      - Caule Black Gray Glass
      - Default
